1) sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (61)")
  a) Port wrong. For me, change to 8889

2) NameError: global name 'db1' is not defined
  a) db argument passed incorrectly

3) mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
  a) Correct the password

4) sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root1'@'localhost' (using password: YES)")
  a) Make sure the username is specified correctly
